### ISSUE TITLE
Shouldn't "get.entity.name()" be converted into "get.luaentity().name" on Line 56 of the init.lua?

### ISSUE THREAD

**Issue by FriendlyGamer** [MultiCraft-Community/cleaner#1]
It was spamming my 5.4.1 server's logs so I tried making this change myself and it appeared it's stopped so I was thinking to bring this to your attention.

Was my "hotfix" correct? Or is more work needs to be done further than that?

**Comment by MoNTE48** [comment]
@FriendlyGamer 
```
- local entname = obj:get_entity_name()
+ local entname = obj:get_luaentity()
```

**Comment by FriendlyGamer** [comment]
> @FriendlyGamer
> 
> ```
> - local entname = obj:get_entity_name()
> + local entname = obj:get_luaentity()
> ```

Awesome thank you very much! I dropped the ".name" at the end as you presented them to me there.
